// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ig5nhzDTm--DFaALFRQYwP31vobT3WM',
    appId: '1:257658860675:web:dea7a61292f9e5946c57b6',
    messagingSenderId: '257658860675',
    projectId: 'qhawekazi-4cdea',
    authDomain: 'qhawekazi-4cdea.firebaseapp.com',
    storageBucket: 'qhawekazi-4cdea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXCCvxri0fa8ZgllR_7WVGug67bG8cklE',
    appId: '1:257658860675:android:452c500be7028cc76c57b6',
    messagingSenderId: '257658860675',
    projectId: 'qhawekazi-4cdea',
    storageBucket: 'qhawekazi-4cdea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKO0yCrFwaz1iqIMkEItmg7Z-kxFwEMkI',
    appId: '1:257658860675:ios:b4211eee5a22bd086c57b6',
    messagingSenderId: '257658860675',
    projectId: 'qhawekazi-4cdea',
    storageBucket: 'qhawekazi-4cdea.firebasestorage.app',
    iosClientId: '257658860675-464vr5l9ea6eml675kren1ofdo2slc2o.apps.googleusercontent.com',
    iosBundleId: 'com.musicteam.musicTeamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5ig5nhzDTm--DFaALFRQYwP31vobT3WM',
    appId: '1:257658860675:web:d3f5a85090c2aacf6c57b6',
    messagingSenderId: '257658860675',
    projectId: 'qhawekazi-4cdea',
    authDomain: 'qhawekazi-4cdea.firebaseapp.com',
    storageBucket: 'qhawekazi-4cdea.firebasestorage.app',
  );

}